theme: jekyll-theme-startbootstrap-agency

title: Kelly and Andrew
description: 'Champion Lindy hop social dancers, competitors, teachers'
author: 'Andrew Jose'

sass:
  style: compressed

assets_path: '' 

collections:
  projects:
